# Generated by Django 4.2.25 on 2025-10-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislative_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('proposicoes_apresentadas', models.IntegerField(default=0)),
                ('votacoes_participadas', models.IntegerField(default=0)),
                ('discursos_realizados', models.IntegerField(default=0)),
                ('principais_atuacoes', models.JSONField(default=list)),
                ('destaque_periodo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='legislative_monitor.deputado')),
            ],
            options={
                'verbose_name': 'Relatório de Atividade',
                'verbose_name_plural': 'Relatórios de Atividades',
                'ordering': ['-data_fim'],
            },
        ),
        migrations.CreateModel(
            name='PerfilParlamentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votacoes', models.IntegerField(default=0)),
                ('presenca_votacoes', models.FloatField(default=0.0, help_text='Percentual de presença')),
                ('votos_sim', models.IntegerField(default=0)),
                ('votos_nao', models.IntegerField(default=0)),
                ('votos_abstencao', models.IntegerField(default=0)),
                ('total_proposicoes', models.IntegerField(default=0)),
                ('proposicoes_aprovadas', models.IntegerField(default=0)),
                ('proposicoes_em_tramitacao', models.IntegerField(default=0)),
                ('total_discursos', models.IntegerField(default=0)),
                ('tempo_total_discurso', models.IntegerField(default=0, help_text='Tempo em minutos')),
                ('areas_atuacao', models.JSONField(default=list, help_text='Áreas temáticas de atuação')),
                ('temas_frequentes', models.JSONField(default=list, help_text='Temas mais abordados')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deputado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='legislative_monitor.deputado')),
            ],
            options={
                'verbose_name': 'Perfil Parlamentar',
                'verbose_name_plural': 'Perfis Parlamentares',
            },
        ),
        migrations.CreateModel(
            name='ComparativoDeputados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('criterios', models.JSONField(default=list)),
                ('resultados', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deputados', models.ManyToManyField(related_name='comparativos', to='legislative_monitor.deputado')),
            ],
            options={
                'verbose_name': 'Comparativo de Deputados',
                'verbose_name_plural': 'Comparativos de Deputados',
                'ordering': ['-created_at'],
            },
        ),
    ]
