# Generated by Django 4.2.25 on 2025-10-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_deputado', models.IntegerField(help_text='ID do deputado na API da Câmara', unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('nome_civil', models.CharField(blank=True, max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('sexo', models.CharField(blank=True, max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('municipio_nascimento', models.CharField(blank=True, max_length=255)),
                ('uf_nascimento', models.CharField(blank=True, max_length=2)),
                ('sigla_partido', models.CharField(max_length=20)),
                ('uf_representacao', models.CharField(max_length=2)),
                ('situacao', models.CharField(blank=True, max_length=50)),
                ('condicao_eleitoral', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url_website', models.URLField(blank=True)),
                ('url_foto', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deputado',
                'verbose_name_plural': 'Deputados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proposicao', models.IntegerField(help_text='ID da proposição na API da Câmara', unique=True)),
                ('tipo', models.CharField(choices=[('PL', 'Projeto de Lei'), ('PLP', 'Projeto de Lei Complementar'), ('PEC', 'Proposta de Emenda à Constituição'), ('PDC', 'Projeto de Decreto Legislativo'), ('PRC', 'Projeto de Resolução'), ('MPV', 'Medida Provisória')], max_length=10)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('ementa', models.TextField()),
                ('ementa_detalhada', models.TextField(blank=True)),
                ('data_apresentacao', models.DateField()),
                ('situacao', models.CharField(choices=[('EM_TRAMITACAO', 'Em Tramitação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('ARQUIVADA', 'Arquivada'), ('RETIRADA', 'Retirada')], default='EM_TRAMITACAO', max_length=50)),
                ('status_proposicao', models.TextField(blank=True)),
                ('url_inteiro_teor', models.URLField(blank=True)),
                ('url_tramitacao', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposicoes', to='legislative_monitor.deputado')),
            ],
            options={
                'verbose_name': 'Proposição',
                'verbose_name_plural': 'Proposições',
                'ordering': ['-data_apresentacao'],
            },
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_votacao', models.CharField(max_length=100, unique=True)),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('tipo_votacao', models.CharField(max_length=100)),
                ('aprovacao', models.BooleanField(blank=True, null=True)),
                ('votos_sim', models.IntegerField(default=0)),
                ('votos_nao', models.IntegerField(default=0)),
                ('votos_abstencao', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacoes', to='legislative_monitor.proposicao')),
            ],
            options={
                'verbose_name': 'Votação',
                'verbose_name_plural': 'Votações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Discurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_discurso', models.CharField(max_length=100, unique=True)),
                ('data', models.DateTimeField()),
                ('tipo_discurso', models.CharField(max_length=100)),
                ('transcricao', models.TextField()),
                ('sumario', models.TextField(blank=True)),
                ('url_audio', models.URLField(blank=True)),
                ('url_video', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discursos', to='legislative_monitor.deputado')),
            ],
            options={
                'verbose_name': 'Discurso',
                'verbose_name_plural': 'Discursos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='VotoDeputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('ABSTENCAO', 'Abstenção'), ('OBSTRUCAO', 'Obstrução'), ('AUSENTE', 'Ausente')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='legislative_monitor.deputado')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='legislative_monitor.votacao')),
            ],
            options={
                'verbose_name': 'Voto do Deputado',
                'verbose_name_plural': 'Votos dos Deputados',
                'unique_together': {('votacao', 'deputado')},
            },
        ),
    ]
