# Generated by Django 4.2.25 on 2025-10-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Código do IBGE do Estado', primary_key=True, serialize=False)),
                ('sigla', models.CharField(help_text='Sigla do Estado', max_length=2, unique=True)),
                ('nome', models.CharField(help_text='Nome do Estado', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Código do IBGE da Região', primary_key=True, serialize=False)),
                ('sigla', models.CharField(help_text='Sigla da Região', max_length=2, unique=True)),
                ('nome', models.CharField(help_text='Nome da Região', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Código do IBGE do Município', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do Município', max_length=100)),
                ('is_capital', models.BooleanField(default=False, help_text='Indica se o município é a capital do Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(help_text='Estado do Município', on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='legislative_monitor.estado')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='regiao',
            field=models.ForeignKey(help_text='Região do Estado', on_delete=django.db.models.deletion.PROTECT, related_name='estados', to='legislative_monitor.regiao'),
        ),
        migrations.AddConstraint(
            model_name='municipio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_capital', True)), fields=('estado',), name='unique_capital_per_state'),
        ),
    ]
