# Generated by Django 5.2.7 on 2025-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_monitor', '0002_estado_regiao_municipio_estado_regiao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(help_text='Código do tipo de proposição na API da Câmara', max_length=10, unique=True)),
                ('sigla', models.CharField(db_index=True, help_text='Sigla do tipo de proposição', max_length=20)),
                ('nome', models.CharField(help_text='Nome completo do tipo de proposição', max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do tipo de proposição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Proposição',
                'verbose_name_plural': 'Tipos de Proposição',
                'ordering': ['sigla', 'nome'],
                'indexes': [models.Index(fields=['sigla'], name='legislative_sigla_c0eba1_idx'), models.Index(fields=['cod'], name='legislative_cod_35072a_idx')],
            },
        ),
    ]
