# Generated by Django 5.2.7 on 2025-10-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_monitor', '0003_tipoproposicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='tipo_proposicao',
            field=models.ForeignKey(blank=True, help_text='Tipo de proposição conforme API da Câmara', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposicoes', to='legislative_monitor.tipoproposicao'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PL', 'Projeto de Lei'), ('PLP', 'Projeto de Lei Complementar'), ('PEC', 'Proposta de Emenda à Constituição'), ('PDC', 'Projeto de Decreto Legislativo'), ('PRC', 'Projeto de Resolução'), ('MPV', 'Medida Provisória')], max_length=10),
        ),
    ]
