# Generated by Django 5.2.7 on 2025-10-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_monitor', '0004_add_tipo_proposicao_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Sigla do sexo (ex: M, F, NB)', max_length=2, unique=True)),
                ('nome', models.CharField(help_text='Nome completo do sexo/gênero', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição gerada automaticamente por IA', max_length=500)),
                ('slug', models.SlugField(blank=True, help_text='Slug gerado automaticamente a partir do nome', max_length=120, unique=True)),
                ('_nome_anterior', models.CharField(blank=True, editable=False, help_text='Nome anterior para detectar mudanças', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'ordering': ['sigla'],
            },
        ),
        migrations.AddField(
            model_name='deputado',
            name='municipio_nascimento_obj',
            field=models.ForeignKey(blank=True, help_text='Município de nascimento do deputado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputados_nascidos', to='legislative_monitor.municipio'),
        ),
        migrations.AddField(
            model_name='deputado',
            name='uf_nascimento_obj',
            field=models.ForeignKey(blank=True, help_text='Estado de nascimento do deputado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputados_nascidos', to='legislative_monitor.estado'),
        ),
        migrations.AddField(
            model_name='deputado',
            name='uf_representacao_obj',
            field=models.ForeignKey(blank=True, help_text='Estado de representação do deputado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deputados_representantes', to='legislative_monitor.estado'),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='municipio_nascimento',
            field=models.CharField(blank=True, help_text='Campo legado - usar municipio_nascimento_obj', max_length=255),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='sexo',
            field=models.CharField(blank=True, help_text='Campo legado - usar sexo_obj', max_length=1),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='uf_nascimento',
            field=models.CharField(blank=True, help_text='Campo legado - usar uf_nascimento_obj', max_length=2),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='uf_representacao',
            field=models.CharField(help_text='Campo legado - usar uf_representacao_obj', max_length=2),
        ),
        migrations.AddField(
            model_name='deputado',
            name='sexo_obj',
            field=models.ForeignKey(blank=True, help_text='Sexo/gênero do deputado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputados', to='legislative_monitor.sexo'),
        ),
    ]
