# Generated by Django 5.2.7 on 2025-10-29 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_monitor', '0005_refactor_deputado_direct_relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposicao',
            name='tipo_proposicao',
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo de proposição conforme API da Câmara', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposicoes', to='legislative_monitor.tipoproposicao'),
        ),
    ]
