# Generated by Django 5.2.7 on 2025-10-29 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_monitor', '0006_refactor_proposicao_tipo_direct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partido', models.IntegerField(help_text='ID do partido na API da Câmara', unique=True)),
                ('sigla', models.CharField(db_index=True, help_text='Sigla do partido', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Nome completo do partido', max_length=255)),
                ('uri', models.URLField(blank=True, help_text='URI do partido na API da Câmara')),
                ('status_data', models.DateTimeField(blank=True, help_text='Data da última atualização do status', null=True)),
                ('status_situacao', models.CharField(blank=True, help_text='Situação do partido (Ativo, Inativo, etc.)', max_length=50)),
                ('status_total_posse', models.IntegerField(blank=True, help_text='Total de deputados que tomaram posse pelo partido', null=True)),
                ('status_total_membros', models.IntegerField(blank=True, help_text='Total de membros atuais do partido', null=True)),
                ('status_id_legislatura', models.IntegerField(blank=True, help_text='ID da legislatura do status', null=True)),
                ('numero_eleitoral', models.IntegerField(blank=True, help_text='Número eleitoral do partido', null=True)),
                ('url_logo', models.URLField(blank=True, help_text='URL do logo do partido')),
                ('url_website', models.URLField(blank=True, help_text='URL do website oficial do partido')),
                ('url_facebook', models.URLField(blank=True, help_text='URL da página do Facebook do partido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['sigla'],
                'indexes': [models.Index(fields=['sigla'], name='legislative_sigla_8320b4_idx'), models.Index(fields=['id_partido'], name='legislative_id_part_8f9757_idx')],
            },
        ),
        migrations.AlterField(
            model_name='deputado',
            name='sigla_partido',
            field=models.ForeignKey(blank=True, help_text='Partido político do deputado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputados', to='legislative_monitor.partido'),
        ),
    ]
