# Generated by Django 5.2.7 on 2025-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_monitor', '0007_add_partido_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='url_facebook',
            field=models.URLField(blank=True, help_text='URL da página do Facebook do partido', null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='url_website',
            field=models.URLField(blank=True, help_text='URL do website oficial do partido', null=True),
        ),
    ]
