# Generated by Django 4.2.25 on 2025-10-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislative_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField()),
                ('resumo_executivo', models.TextField(blank=True)),
                ('principais_pontos', models.JSONField(default=list)),
                ('modelo_ia', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_ia', to='legislative_monitor.proposicao')),
            ],
            options={
                'verbose_name': 'Resumo IA',
                'verbose_name_plural': 'Resumos IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuscaSemantica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(help_text='Vetor de embedding para busca semântica')),
                ('texto_indexado', models.TextField()),
                ('modelo_embedding', models.CharField(default='text-embedding-ada-002', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_semantico', to='legislative_monitor.proposicao')),
            ],
            options={
                'verbose_name': 'Busca Semântica',
                'verbose_name_plural': 'Buscas Semânticas',
            },
        ),
        migrations.CreateModel(
            name='AnaliseImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_impacto', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], max_length=20)),
                ('descricao_impacto', models.TextField()),
                ('areas_afetadas', models.JSONField(default=list)),
                ('stakeholders', models.JSONField(default=list)),
                ('impacto_economico', models.TextField(blank=True)),
                ('impacto_social', models.TextField(blank=True)),
                ('impacto_ambiental', models.TextField(blank=True)),
                ('impacto_juridico', models.TextField(blank=True)),
                ('modelo_ia', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_impacto', to='legislative_monitor.proposicao')),
            ],
            options={
                'verbose_name': 'Análise de Impacto',
                'verbose_name_plural': 'Análises de Impacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseDiscurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentimento', models.CharField(blank=True, max_length=50)),
                ('temas_principais', models.JSONField(default=list)),
                ('entidades_mencionadas', models.JSONField(default=list)),
                ('resumo', models.TextField(blank=True)),
                ('modelo_ia', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to='legislative_monitor.discurso')),
            ],
            options={
                'verbose_name': 'Análise de Discurso',
                'verbose_name_plural': 'Análises de Discursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
